### PR TITLE
I got `FanControl` added to `Scoop`.

### PR DESCRIPTION
**Pull request by Zliced13**
Hello @Rem0o,

I recently had **FanControl** added to Scoop. If you don't know what Scoop is, it's a package manager for Windows, maintained by the Scoop community. 

Scoop can be installed into your Windows OS by following the instructions [here](https://scoop.sh/). After Scoop is installed in your system, you can install **FanControl** with the following commands:

_First_
```
scoop bucket add extras
```
_Second_
```
scoop install fancontrol
```

### CODE REVIEW

**Comment by Impact123** [comment]
I'm curious why you chose a hyphen for the package name.

**Comment by Zliced13** [comment]
> I'm curious why you chose a hyphen for the package name.

It's the name I  decided to chose for the app manifest. However if this is causing issues, I can try to make a PR that will rename **fan-control** to **fancontrol**.

**Comment by grrttedwards** [comment]
I just happened to try to install this via scoop without knowing if it were there or not, and was surprised that the name includes a hyphen. I would suggest removing it in the manifest.

**Comment by Rem0o** [comment]
Questions:

1) How's the versioning of the binaries on scoop will be managed?

**Comment by Zliced13** [comment]
> Questions:
> 
> 1. How's the versioning of the binaries on scoop will be managed?

What do you mean by, "versioning of the binaries"? Are you talking about 'auto-update'?

**Comment by Rem0o** [comment]
@Zliced13  Nvm found the manifest: 

https://github.com/ScoopInstaller/Extras/blob/master/bucket/fan-control.json

My question is basically, how is this manifest maintained? I can see some kind of github action seems to be monitoring github releases and automatically updating the manifest file. I guess I need to maintain consistency with my zip files naming for this to work?

**Comment by Zliced13** [comment]
@Rem0o The manifest has been renamed from `fan-control` to `fancontrol`, I hope this works well for everyone.

**Comment by Impact123** [comment]
The now merged change refers to `fan-control`

**Comment by Zliced13** [comment]
@Rem0o could you please change `fan-control` to `fancontrol`? I forgot to change it in the markdown document.

**Comment by Rem0o** [comment]
Done.

**Pull request merged**
